//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Educations = new HashSet<Education>();
            this.Skills = new HashSet<Skill>();
            this.WorkExperiences = new HashSet<WorkExperience>();
        }
    
        public int CandID { get; set; }
        public string CandName { get; set; }
        public string CandPhone { get; set; }
        public string Email { get; set; }
        public int CandGender { get; set; }
        public string CandAddress { get; set; }
        public System.DateTime CandBirthday { get; set; }
        public string Interest { get; set; }
        public string AccName { get; set; }
        public Nullable<System.DateTime> Startday { get; set; }
        public string Link { get; set; }
        public string ReReason { get; set; }
        public Nullable<System.DateTime> HasDeleted { get; set; }
        public string Status { get; set; }
        public string Objective { get; set; }
        public string CandMajor { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> UpdateNew { get; set; }
        public Nullable<int> UpdateTimes { get; set; }
        public string HasRejected { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkExperience> WorkExperiences { get; set; }
    }
}
