//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int EduID { get; set; }
        public string Major { get; set; }
        public string School { get; set; }
        public string LevelEdu { get; set; }
        public System.DateTime Startday { get; set; }
        public System.DateTime Endday { get; set; }
        public double GPA { get; set; }
        public int CandID { get; set; }
        public Nullable<System.DateTime> HasDeleted { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
