//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpPhone { get; set; }
        public string EmpEmail { get; set; }
        public string AccName { get; set; }
        public Nullable<System.DateTime> HasDeleted { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
