//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public int ExpID { get; set; }
        public string Position { get; set; }
        public string WorkPlace { get; set; }
        public string WorkTime { get; set; }
        public int CandID { get; set; }
        public Nullable<System.DateTime> HasDeleted { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
